### PR TITLE
Make the caption on images nicer if available

### PR DESCRIPTION
**Pull request by pleasantone**
Currently, the caption is the filename or overridden filename (changed by resources:).
Allow it to be overridden.

```
resources:
- src: filename.jpg or could be a glob...
   name: better name
   title: the title currently that shows up in the hover-over info button
   caption: a specific image caption which you want displayed
```

### CODE REVIEW

**Comment by razonyang** [comment]
LGTM, but the title and caption seems duplicate to me, would mind providing a real use case of using caption different than title?

**Comment by pleasantone** [comment]
Since title was already in use, and people were using it inside the info hover, I was concerned that someone might want something different, and I didn’t want to break that option. Since looks for caption first, which is the new field, then, defaults to title, then defaults to the old file name, it doesn’t cause any additional work to give them the option. I have no objection to removing caption, and just using title. I may have just been overly cautious.

**Comment by razonyang** [comment]
> I may have just been overly cautious.

I think it's for now, since there is only one place (image's alt) we use this, in this case, they are duplicate for the same purpose.

**Review by razonyang — APPROVED** [review]

**Comment by razonyang** [comment]
I made some change, the title will be used as alternative text of image if provided, default to filename.
As to the caption, the order is 1) `Params.caption` 2) The alternative text mentioned above.

**Pull request merged**
